version: 2
jobs:
  build:
    docker:
      - image: florianwechsung/firedrake:latest
      
    working_directory: ~/repo

    steps:
      - checkout
      - run: . /firedrake/bin/activate; pip3 install wheel --upgrade
      - run: . /firedrake/bin/activate; pip3 install scipy
      - run: . /firedrake/bin/activate; pip3 install roltrilinos
      - run: . /firedrake/bin/activate; pip3 install ROL
      - run: . /firedrake/bin/activate; cd repo; export PYTHONPATH=$(pwd):$PYTHONPATH; pytest
            
